name: kg-llm-bench
channels:
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyg
  - networkx
  - jsbeautifier
  - openai
  - pandas
  - matplotlib
  - pyyaml
  - google-generativeai
  - rdflib
  - python-dotenv
  - google-generativeai
  - grpcio
  - langchain-aws

