from .base_task import BaseTask, TripleRetrievalTask
from .agg_neighbor_properties_task import AggNeighborPropertiesTask
from .highest_degree_node_task import HighestDegreeNodeTask
from .agg_by_relation_task import AggByRelationTask
from .shortest_path_task import ShortestPathTask