llm_configs:
  - model: 'gpt-4o-mini'
    provider: 'openai'
#  - model: 'gemini-1.5-flash-8b'
#    provider: 'google'
pseudonomizer_configs:
  - 'pseudonym_file': 'data/countries/pseudonym_data/country_pseudonyms.tsv'
  - null
task_configs:
  - type: TripleRetrievalTask
    base_dataset_file: 'TripleRetrieval_small.json'
    dataset_file: 'TripleRetrieval_small.json'
    results_file: 'small_results.json'
  - type: ShortestPathTask
    base_dataset_file: 'ShortestPath_small.json'
    dataset_file: 'ShortestPath_small.json'
    results_file: 'small_results.json'
  - type: HighestDegreeNodeTask
    base_dataset_file: 'HighestDegree_small.json'
    dataset_file: 'HighestDegree_small.json'
    results_file: 'small_results.json'
  - type: AggByRelationTask
    base_dataset_file: AggByRelation_small.json
    dataset_file: 'AggByRelation_small.json'
    results_file: 'small_results.json'
  - type: AggNeighborPropertiesTask
    base_dataset_file: AggNeighborProperties_small.json'
    dataset_file: 'AggNeighborProperties_small.json'
    results_file: 'small_results.json'
conversion_configs:
  - type: list_of_edges
  # - type: structured_yaml
  # - type: structured_json
  # - type: TURTLE
  # - type: GraphSON
  # - type: NetworkX_edge_list
  # - type: GML
  # - type: relation_database_csvs
